name: Provision AWS Resources

on:
  workflow_dispatch:

env:
  TF_IN_AUTOMATION: true

permissions:
  id-token: write

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Configure AWS Credentials for S3 Backend
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          role-to-assume: arn:aws:iam::501046919017:role/GithubActionsTerraformS3Backend
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
            terraform_version: "1.14.7"

      - name: Terraform Init
        run: |
            terraform init -input=false

      - name: Configure AWS Credentials for Resource Provisioning
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          role-to-assume: arn:aws:iam::501046919017:role/GithubActionsTerraformAdmin
          aws-region: us-east-1

      - name: Terraform Plan
        run: terraform plan -out=tfplan -input=false

      - name: Build Artifact
        uses: actions/upload-artifact@v7
        with:
          name: planned-terraform-configuration
          path: .
          include-hidden-files: true
          if-no-files-found: error
          retention-days: 1
          overwrite: true

  terraform-apply:
    needs: terraform-plan
    runs-on: ubuntu-latest
    environment: TRAINING

    steps:
      - name: Install Artifact
        uses: actions/download-artifact@v8
        with:
          name: planned-terraform-configuration

      - name: Configure AWS Credentials for Resource Provisioning
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          role-to-assume: arn:aws:iam::501046919017:role/GithubActionsTerraformAdmin
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
            terraform_version: "1.14.7"

      - name: Terraform Apply
        run: terraform apply -input=false tfplan
